### ISSUE TITLE
Make rules configurable

### ISSUE THREAD

**Issue by dorzey** [autotraderuk/oliver-twist#10] opened 2020-12-22 16:12 UTC
Read rule configuration from a single config yml file
```
global:
    - id: <rule_name_1>
      enabled: false
    - id: <rule_name_2>
      enabled: false
```

All rules will be enabled be default.

**Comment by bloomonkey** [comment] 2020-12-22 16:35
Is this a duplicate of #2 ?

**Comment by dorzey** [comment] 2020-12-22 16:53
It is probably the first step to fully enable that

**Closed** 2020-12-23 13:56 UTC
